import 'package:ecommerceriverpod/src/features/products/domain/product.dart';

/// Test products to be used until a data source is implemented
var kTestProducts = [
  Product(
    itemsId: 1,
    // imageUrl: 'assets/products/bruschetta-plate.jpg',
    itemsName: 'Bruschetta plate',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 15,
    // itemsCount: 5,
    // avgRating: 4.5,
    // numRatings: 2,
  ),
  Product(
    itemsId: 2,
    // imageUrl: 'assets/products/mozzarella-plate.jpg',
    itemsName: 'Mozzarella plate',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 13,
    // itemsCount: 5,
    // avgRating: 4,
    // numRatings: 2,
  ),
  Product(
    itemsId: 3,
    // imageUrl: 'assets/products/pasta-plate.jpg',
    itemsName: 'Pasta plate',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 17,
    // itemsCount: 5,
    // avgRating: 5,
    // numRatings: 2,
  ),
  Product(
    itemsId: 4,
    // imageUrl: 'assets/products/piggy-blue.jpg',
    itemsName: 'Piggy Bank Blue',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 12,
    // itemsCount: 5,
  ),
  Product(
    itemsId: 5,
    // imageUrl: 'assets/products/piggy-green.jpg',
    itemsName: 'Piggy Bank Green',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 12,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 6,
    // imageUrl: 'assets/products/piggy-pink.jpg',
    itemsName: 'Piggy Bank Pink',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 12,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 7,
    // imageUrl: 'assets/products/pizza-plate.jpg',
    itemsName: 'Pizza plate',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 18,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 8,
    // imageUrl: 'assets/products/plate-and-bowl.jpg',
    itemsName: 'Plate and Bowl',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 21,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 9,
    // imageUrl: 'assets/products/salt-pepper-lemon.jpg',
    itemsName: 'Salt and pepper lemon',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 11,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 10,
    // imageUrl: 'assets/products/salt-pepper-olives.jpg',
    itemsName: 'Salt and pepper olives',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 11,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 11,
    // imageUrl: 'assets/products/snacks-plate.jpg',
    itemsName: 'Snacks plate',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 24,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 12,
    // imageUrl: 'assets/products/flowers-plate.jpg',
    itemsName: 'Flowers plate',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 22,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 13,
    // imageUrl: 'assets/products/juicer-citrus-fruits.jpg',
    itemsName: 'Juicer for citrus fruits',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 14,
    // itemsCount: 10,
  ),
  Product(
    itemsId: 14,
    // imageUrl: 'assets/products/honey-pot.jpg',
    itemsName: 'Honey pot',
    itemsDesc: 'Lorem ipsum',
    // itemsPrice: 16,
    // itemsCount: 10,
  ),
];
